from typing import Any, Dict, List, Optional

class Tables:
    def __init__(self, version: str, dataroot: str) -> None: ...
    def get(self, table: str, token: str) -> Dict[str, Any]: ...
    @property
    def log(self) -> List[Dict[str, Any]]: ...
    @property
    def map(self) -> List[Dict[str, Any]]: ...
    @property
    def sensor(self) -> List[Dict[str, Any]]: ...
    @property
    def calibrated_sensor(self) -> List[Dict[str, Any]]: ...
    @property
    def scene(self) -> List[Dict[str, Any]]: ...
    @property
    def sample(self) -> List[Dict[str, Any]]: ...
    @property
    def sample_data(self) -> List[Dict[str, Any]]: ...
    @property
    def ego_pose(self) -> List[Dict[str, Any]]: ...
    @property
    def instance(self) -> List[Dict[str, Any]]: ...
    @property
    def sample_annotation(self) -> List[Dict[str, Any]]: ...
    @property
    def category(self) -> List[Dict[str, Any]]: ...
    @property
    def attribute(self) -> List[Dict[str, Any]]: ...
    @property
    def lidarseg(self) -> Optional[List[Dict[str, Any]]]: ...
    @property
    def panoptic(self) -> Optional[List[Dict[str, Any]]]: ...
